---
sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - blead
  - blead-thr
  - dev
  - dev-thr
  - 5.24.0
  - 5.24.0-thr
  - 5.22.1
  - 5.22.1-thr
  - 5.20.3
  - 5.20.3-thr
  - 5.18.3
  - 5.18.3-thr
  - 5.16.3
  - 5.16.3-thr
  - 5.14.4
  - 5.14.4-thr
matrix:
  allow_failures:
    - perl: blead
    - perl: blead-thr
  include:
    - env: COVERAGE=1
      perl: '5.24'
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "PGfC0fdw2itviHcAhEvfOFbxjBbMTYMQZUdNOdKAVBxUjRcr0cnem6GTHqGI2g+L2ft3vkAV7+1RBjOcN/jWUyMLWR9Eto6R33Z8jfchiFVxTJMZiZgBS2TxgwRn0eZpLRXKTLftKa7hK7sHTeRXnlC8VYNEb/USWkm6ST/e5eI=\n"
